#!/bin/bash
# Скрипт для створення .env файлу з GitHub Secrets
# Використовується в GitHub Actions workflow

cat > .env << EOF
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
DATABASE_URL=${DATABASE_URL}
JWT_SECRET=${JWT_SECRET}
APP_ENV=prod
SMTP_HOST=${SMTP_HOST:-}
SMTP_PORT=${SMTP_PORT:-587}
SMTP_USER=${SMTP_USER:-}
SMTP_PASSWORD=${SMTP_PASSWORD:-}
SMTP_FROM=${SMTP_FROM:-}
TELEGRAM_ENABLED=${TELEGRAM_ENABLED:-false}
TELEGRAM_API_ID=${TELEGRAM_API_ID:-}
TELEGRAM_API_HASH=${TELEGRAM_API_HASH:-}
TELEGRAM_SESSION_STRING=${TELEGRAM_SESSION_STRING:-}
TELEGRAM_SENDER_NAME=${TELEGRAM_SENDER_NAME:-}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
INPOST_API_KEY=${INPOST_API_KEY:-}
WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN:-}
WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID:-}
WHATSAPP_APP_SECRET=${WHATSAPP_APP_SECRET:-}
WHATSAPP_VERIFY_TOKEN=${WHATSAPP_VERIFY_TOKEN:-}
FACEBOOK_ACCESS_TOKEN=${FACEBOOK_ACCESS_TOKEN:-}
FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET:-}
FACEBOOK_VERIFY_TOKEN=${FACEBOOK_VERIFY_TOKEN:-}
FACEBOOK_PAGE_ID=${FACEBOOK_PAGE_ID:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
REDIS_URL=${REDIS_URL:-redis://localhost:6379/0}
FRONTEND_URL=${FRONTEND_URL:-https://tlumaczeniamt.com.pl}
IMAP_HOST=${IMAP_HOST:-}
IMAP_PORT=${IMAP_PORT:-993}
EOF

